FROM oven/bun:1

WORKDIR /app

ARG DATABASE_URL

COPY ../packages ./packages

COPY ../bun.lock ./bun.lock

COPY ../apps/backend/package*.json ./apps/backend/

COPY ../apps/web ./apps/web

COPY . .

RUN bun install

RUN bun run db:generate 

RUN DATABASE_URL=${DATABASE_URL} bun run build




EXPOSE 3000

CMD ["bun", "run", "start:web"]
