FROM oven/bun:1

WORKDIR /app

COPY packages ./packages

COPY bun.lock ./bun.lock

COPY apps/backend/package*.json ./apps/backend/

COPY apps/backend ./apps/backend

COPY . .

RUN bun install

RUN bun run db:generate 





EXPOSE 8080

CMD ["bun", "run", "start:backend"]
