# BUILD THE DOCKER IMAGE
name: Build and Deploy Backend

on:
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.BackEnd
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:${{ github.sha }}   
      - name: Deploy to server
        run: |
          echo "${ secrets.SSH_PRIVATE_KEY }" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@${{ secrets.SSH_HOST }} -t "docker stop todo-app-backend && docker run --name todo-app-backend -d -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:${{ github.sha }}"