# # BUILD THE DOCKER IMAGE
# name: Build and Deploy frontend

# on:
#   push:
#     branches: [ main ]

# jobs: 
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./docker/Dockerfile.FrontEnd
#           push: true
#           tags: ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:${{ github.sha }}  

#       - name: Deploy to server
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: root
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             docker pull ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:${{ github.sha }}
#             docker stop todo-app-frontend || true
#             docker rm todo-app-frontend || true
#             docker run --name todo-app-frontend -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/todo-app-frontend:${{ github.sha }}